name: automatic-release-windows-intelLLVM

on:
  push:
    branches:
      - main

jobs:

  builds-and-tests:
    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: 'intelmpi'

    - name: Setup intel fortran
      uses: fortran-lang/setup-fortran@v1
      id: setup-fortran
      with:
        compiler: intel
        version: '2024.0'    
    
    - name: Setup ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: CMake build
      shell: bash
      run: |
        .github/workflows/build_windows.bat
          
    - name: Install python wrapper requirements
      run: |
        python -m pip install -r requirements.txt

    - name: Run all tests 
      shell: bash
      timeout-minutes: 120
      run: |
        .github/workflows/run_tests_windows.bat
    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Creating archive
      run: |
          tar -czvf semba-fdtd-windows-intelLLVM.tar.gz build/bin/* LICENSE

    - name: Generating release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ steps.date.outputs.date }}-windows-intelLLVM"
        prerelease: false
        title: "${{ steps.date.outputs.date }} Windows Intel LLVM dev. build"
        files: |
          semba-fdtd-windows-intelLLVM.tar.gz

