name: ubuntu-intelLLVM

on:

  pull_request:
    branches:
      - main
      - dev 

jobs:

  builds-and-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        optimization-type: ["Debug", "Release"]
        mpi-build: ["No", "Yes"]

    name: ubuntu-intelLLVM ${{matrix.build-type}} - mpi ${{matrix.mpi}} - mtln ${{matrix.mtln}}

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: 'intelmpi'

    - name: Setup intel fortran
      uses: fortran-lang/setup-fortran@v1
      id: setup-fortran
      with:
        compiler: intel
        version: '2024.2'

    - name: CMake build
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=${{matrix.optimization-type}} -DSEMBA_FDTD_ENABLE_MPI=${{matrix.mpi-build}} -DSEMBA_FDTD_ENABLE_HDF=YES
        cmake --build build -j
        
    - name: Run fdtd unit tests
      timeout-minutes: 60
      run: |
        build/bin/fdtd_tests

    - name: Install python wrapper requirements
      run: |
        python -m pip install -r requirements.txt

    - name: Run wrapper tests
      timeout-minutes: 60
      run: |
        python -m pytest test    