name: ubuntu-gnu

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  
  builds-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        build-type: ["Debug", "Release"]
        mpi: ["No", "Yes"]
        mtln: ["Yes"]
        include:
          - build-type: "Release"
            mpi: "Yes"
            mtln: "No"

    name: ubuntu ${{matrix.build-type}} - mpi ${{matrix.mpi}} - mtln ${{matrix.mtln}}

    steps:       
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Install required packages
      run: |
        sudo apt update
        sudo apt install libhdf5-dev libopenmpi-dev
   
    - name: Build application
      run: |       
        cmake -S . -B build -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DSEMBA_FDTD_ENABLE_MPI=${{matrix.mpi}} -DSEMBA_FDTD_ENABLE_MTLN=${{matrix.mtln}}
        cmake --build build -j
      
    - name: Run fdtd unit tests 
      run: |
        build/bin/fdtd_tests

    - name: Install python wrapper requirements
      run: |
        python -m pip install -r requirements.txt

    - name: Run wrapper tests
      run: |
        python -m pytest test
       
      
