name: ubuntu-intel

on:
  pull_request:
    branches:
      - main
      - dev 

jobs:

  builds-and-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        build-type: ["Debug", "Release"]
        mpi: ["No"]
        mtln: ["No"]
        hdf: ["Yes"]


    name: ${{matrix.build-type}}- mpi ${{matrix.mpi}} - mtln ${{matrix.mtln}} - hdf ${{matrix.hdf}}

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: 'intelmpi'

    - name: Setup intel fortran
      uses: fortran-lang/setup-fortran@v1
      id: setup-fortran
      with:
        compiler: intel-classic
        version: '2021.10'

    - name: CMake build
      run: |
        cmake -S . -B build \
          -DCMAKE_BUILD_TYPE=${{matrix.build-type}} \
          -DSEMBA_FDTD_ENABLE_MPI=${{matrix.mpi}} \
          -DSEMBA_FDTD_ENABLE_HDF=${{matrix.hdf}} \
          -DSEMBA_FDTD_ENABLE_MTLN=${{matrix.mtln}}
        cmake --build build -j
        
    - name: Run fdtd unit tests
      timeout-minutes: 60
      run: |
        build/bin/fdtd_tests

    - name: Install python wrapper requirements
      run: |
        python -m pip install -r requirements.txt

    - name: Run all wrapper tests
      if: matrix.mtln=='Yes'
      run: python -m pytest test/
        
    - name: Run non-mtln wrapper tests
      if: matrix.mtln=='No'
      run: python -m pytest -m 'not mtln' test/