name: ubuntu-nvhpc

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  builds-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        build-type: ["Debug", "Release"]
        mpi: ["No"]
        mtln: ["No"]
        hdf: ["No"]

    name: ${{matrix.build-type}}- mpi ${{matrix.mpi}} - mtln ${{matrix.mtln}} - hdf ${{matrix.hdf}}

    timeout-minutes: 30
    steps:       
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - uses: fortran-lang/setup-fortran@v1
      id: setup-fortran
      with:
        compiler: nvidia-hpc
        version: '24.5'

    - name: Install required packages
      run: |
        sudo apt update
        sudo apt install libhdf5-dev libopenmpi-dev
      
    - name: Build application
      run: |
        cmake -S . -B build \
          -DCMAKE_BUILD_TYPE=${{matrix.build-type}} \
          -DSEMBA_FDTD_ENABLE_MPI=${{matrix.mpi}} \
          -DSEMBA_FDTD_ENABLE_HDF=${{matrix.hdf}} \
          -DSEMBA_FDTD_ENABLE_MTLN=${{matrix.mtln}}
        cmake --build build -j
      
    - name: Run fdtd unit tests 
      timeout-minutes: 30
      run: |
        build/bin/fdtd_tests

    - name: Install python wrapper requirements
      run: |
        python -m pip install -r requirements.txt
    
    - name: Run non-mtln and non-hdf wrapper tests
      if: matrix.mtln=='No' || matrix.hdf=='No' 
      run: python -m pytest -m 'not mtln and not hdf5' test/
       
      