name: ubuntu-gnu

permissions:
  actions: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
env:
  FDTDTESTS_TOP_DIR: fdtd-tests

jobs:
  builds-and-tests:
    runs-on: ubuntu-latest

    steps:
        
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup ninja
      uses: seanmiddleditch/gha-setup-ninja@master
      
    - name: Build application
      run: |       
        cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
        cmake --build build -j
          
    - name: Run json-parser tests 
      run: |
        ctest --test-dir build/src_json_parser/test/ --output-on-failure
        
      