name: windows-intelLLVM

on:

  pull_request:
    branches:
      - main
      - dev

jobs:

  builds-and-tests:
    runs-on: windows-latest
    strategy:
      matrix: 
        build-type: ["Debug", "Release"]
        mpi: ["No"]
        mtln: ["Yes"]
        hdf: ["Yes"]

        include:
          - build-type: "Release"
            mpi: "No"
            mtln: "No"
            hdf: "Yes"

    name: windows-intelLLVM ${{matrix.build-type}} - mpi ${{matrix.mpi}} - mtln ${{matrix.mtln}}

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: 'intelmpi'

    - name: Setup intel fortran
      uses: fortran-lang/setup-fortran@v1
      id: setup-fortran
      with:
        compiler: intel
        version: '2024.0'

    - name: Setup ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: CMake build
      shell: bash
      run: |
        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=${{matrix.build-type}} \
          -DSEMBA_FDTD_ENABLE_MPI=${{matrix.mpi}} \
          -DSEMBA_FDTD_ENABLE_HDF=${{matrix.hdf}} \
          -DSEMBA_FDTD_ENABLE_MTLN=${{matrix.mtln}}
        cmake --build build -j 
          
    - name: Install python wrapper requirements
      run: |
        python -m pip install -r requirements.txt

    - name: Run all wrapper tests (except codemodel)
      if: matrix.mtln=='Yes'
      run: python -m pytest 'not codemodel' test/
        
    - name: Run non-mtln wrapper tests
      if: matrix.mtln=='No'
      run: python -m pytest -m 'not mtln' test/