name: windows-intelLLVM

on:

  pull_request:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  builds-and-tests:
    runs-on: windows-latest
    strategy:
      matrix:
        compiler: [ {name: 'intel', version: '2024.0'} ]
        build-type: ["Debug", "Release"]
        mpi: ["No"]
        mtln: ["Yes"]
        hdf: ["Yes"]

        include:
          - build-type: "Release"
            mpi: "No"
            mtln: "No"
            hdf: "Yes"

      fail-fast: false

    name: ${{matrix.build-type}}-mpi(${{matrix.mpi}})-mtln(${{matrix.mtln}})-hdf(${{matrix.hdf}})

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Install python wrapper requirements
      run: |
        python -m pip install -r requirements.txt

    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: 'intelmpi'

    - name: Setup intel fortran
      uses: fortran-lang/setup-fortran@v1
      id: setup-fortran
      with:
        compiler: ${{ matrix.compiler.name }}
        version: ${{ matrix.compiler.version }}

    - name: Setup ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: CMake build
      shell: bash
      run: |
        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=${{matrix.build-type}} \
          -DSEMBA_FDTD_ENABLE_MPI=${{matrix.mpi}} \
          -DSEMBA_FDTD_ENABLE_HDF=${{matrix.hdf}} \
          -DSEMBA_FDTD_ENABLE_MTLN=${{matrix.mtln}}
        cmake --build build -j 

    - name: Run fdtd unit tests
      run: |
        build/bin/fdtd_tests.exe      

    - name: Run all wrapper tests (except codemodel)
      if: matrix.mtln=='Yes'
      run: python -m pytest -m 'not codemodel' test/
        